version: "3.8"

services:
#================================
#      POSTGRES
#================================
  db:
    image: postgres:14-alpine
    container_name: movies_db
    restart: always
    volumes:
      - movies_db:/var/lib/postgresql/data/
    env_file:
      - .env

#================================
#       ELK
#================================
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: movies_elk
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    depends_on:
      - db
    volumes:
      - data_elk:/usr/share/elasticsearch/data

#================================
#       WEB APPLICATION
#================================
  web:
    build:
      context: ./app
    image: movies_web
    container_name: movies_web
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app
      - media:/app/media
      - static:/app/static

#================================
#      API
#================================
  api:
    build:
      context: ./api
    image: movies_api
    container_name: movies_api
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - redis
      - elastic

##  ================================
##         NGINX API
##  ================================
  nginx_api:
    image: nginx:1.21.6
    container_name: movies_nginx_api
    restart: always
    volumes:
      - ./nginx/api/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/api/configs:/etc/nginx/conf.d:ro
    depends_on:
      - api
    ports:
      - "81:81"

#================================
#       NGINX WEB
#================================
  nginx_web:
    image: nginx:1.21.6
    container_name: movies_nginx_web
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx/web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/web/configs/:/etc/nginx/conf.d:ro
    depends_on:
      - web
    ports:
      - "80:80"

#================================
#       SWAGGER
#================================
  swagger:
    image: swaggerapi/swagger-ui
    container_name: movies_swagger
    volumes:
      - ./app/swagger/openapi.yaml:/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger.yaml
    depends_on:
      - web

  #================================
  #       ETL
  #================================
  etl_service:
    build:
      context: ./etl
    image: etl_service
    container_name: movies_etl
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - elastic
    command: python3 ./main.py

#================================
#       Redis
#================================
  redis:
    image: redis:7.0
    container_name: movies_redis
    restart: always

#================================
#         NETWORK
#================================
networks:
  movies-network:
    external:
      name: movies-network

#================================
#         NETWORK
#================================
volumes:
  movies_db:
  data_elk:
  media:
  static:
