# Generated by Django 3.2 on 2022-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    CREATE_SCHEMA = 'CREATE SCHEMA IF NOT EXISTS external;'
    SET_SCHEMA = 'SET search_path TO content,external,public;'
    SET_SCHEMA_DEFAULT = 'ALTER ROLE ALL SET search_path TO content,external,public;'

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL([CREATE_SCHEMA, SET_SCHEMA, SET_SCHEMA_DEFAULT]),
        migrations.CreateModel(
            name='EtlServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=125, verbose_name='process')),
                ('start', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'EtlService',
                'verbose_name_plural': 'EtlServices',
                'db_table': 'external"."etl_services',
            },
        ),
    ]
